baseURL: ''
languageCode: en-us
title: Demo for Hugo
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Welcome to our tech blog'
    Content: 'Here you will find a lot of cool information'
  socialIcons:
    - name: facebook
    - url: 'www.facebook.com'
    - name: twitter
    - url: 'www.twitter.com'
    - name: github
    - url: 'www.github.com'

  cover:
   linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - indentifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - indentifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - indentifier: archives
      name: Archives
      url: /archives/
      weight: 30